### PR TITLE
Fix brackets issue

### PR DESCRIPTION
**Pull request by r-barnes**
I used to be more of a bracket minimalist, but now I use them pretty regularly to prevent accidents like this.

I've added brackets to this section and see error-free compilation afterwards.

Fixes:
```
/home/rick/projects/dggridR/src/src/DgOutLocFile.cpp:93:9: error: ‘else’ without a previous ‘if’
   93 |       } else if (type != "NONE") {
      |         ^~~~
/home/rick/projects/dggridR/src/src/DgOutLocFile.cpp:97:4: warning: no return statement in function returning non-void [-Wreturn-type]
   97 |    }
      |    ^
/home/rick/projects/dggridR/src/src/DgOutLocFile.cpp: At global scope:
/home/rick/projects/dggridR/src/src/DgOutLocFile.cpp:99:4: error: expected unqualified-id before ‘return’
   99 |    return file;
      |    ^~~~~~
/home/rick/projects/dggridR/src/src/DgOutLocFile.cpp:101:1: error: expected declaration before ‘}’ token
  101 | } // DgOutLocFile::makeOutLoc
      | ^
```

This change also strips some trailing whitespace. If you have a way to configure your editor to do that automatically each time you save a file, that would help reduce these extraneous changes.

### CODE REVIEW

**Comment by r-barnes** [comment]
@sahrk : Could you get this one?

**Comment by r-barnes** [comment]
@sahrk : Your change seems to have fixed things. All that's left now is to sort out the logging (I'm looking into that) and hopefully we'll be set.

**Comment by sahrk** [comment]
@r-barnes I am against adding another external dependency (e.g. a logging library) unless it's absolutely necessary. What if we created a macro for `cout`, say `dgcout`, and use the DGGRIDR flag to set it to either `std::cout` or the R equivalent? That would take care of most of the remaining cases outside of the `report` function.

**Comment by sahrk** [comment]
@r-barnes for now I think I have a solution that will pass muster at CRAN in branch `rout`. It uses `#ifdef DGGRIDR` to substitute `Rcout`/`Rprintf`/etc. for the corresponding C++/C. I don't have any way to test the R code, but I believe all you will need to do is put the correct `include` statements in the `#ifdef`'s at the top of `DgBase.h` and `shapefil.h`. Calls to `exit()` are also `#ifdef`'d and are no-ops in the dggridR version. 

I can't believe dggridR is the only CRAN project using PROJ4 and/or shapelib (or gdal, which includes both). But there is now no output in the stripped-down PROJ4 included with DGGRID, and I handled the output in shapelib as above.

Please give the branch `rout` a try.

**Comment by r-barnes** [comment]
@sahrk :

The changes you've made seem to be working well so far and I've resubmitted the diff to CRAN. I've made a couple of pull requests (one to master, one to the rout branch) fixing some small issues.

Also, looking at `DGGRID/src/lib/dglib/lib/DgEllipsoidRF.cpp` I see on Line 209:
```
#include <stdlib.h>
#include <stdio.h>
#include <cmath>
#include "dglib/DgBase.h"
```
the last include should be
```
#include <dglib/DgBase.h>
```

Moreover, it looks as though two or more files may have been accidentally merged together here - it's pretty non-standard to have includes in the middle of a file like this.

**Pull request closed without merging**
